disabled_rules: # rule identifiers to exclude from running
  - line_length # 877
opt_in_rules:
  - superfluous_disable_command
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Frameworks-Swift
  - Playgrounds
  - vendor
identifier_name:
  excluded: # excluded via string array
    - id
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 80
    error: 100